export interface ChartResponse {
  name: string;
  id: string;
  preview: string;
  album_name: string;
  album_image: string;
  release_date: string;
  album_artists: { artists_name: string }[];
  rated: number;
}

// ArtistResponse 타입 정의
export interface ArtistResponse {
  name: string;
  id: string;
  image: string;
  spotify_url: string;
  rated: number;
  genres: string[];
}

export interface ReviewResponse {
  review_id: number;
  user_uid: number;
  rated: number;
  contents: string;
  title: string;
  type_id: number;
  comment_id: number;
  created_at: string;
  updated_at: string;
  liked: number;
  comments: string[];
}

// 목데이터

export const reviewDummyData: ReviewResponse[] = [
  {
    review_id: 1,
    user_uid: 101,
    rated: 4.5,
    contents:
      "이 앨범은 정말 놀랍습니다. 모든 트랙이 완벽하게 어우러져 있어요.",
    title: "놀라운 앨범",
    type_id: 1,
    comment_id: 1001,
    created_at: "2023-09-20T12:00:00Z",
    updated_at: "2023-09-21T12:00:00Z",
    liked: 0,
    comments: [],
  },
  {
    review_id: 2,
    user_uid: 102,
    rated: 5,
    contents: "정말 최고입니다! 올해 최고의 앨범이라고 생각합니다.",
    title: "최고의 앨범",
    type_id: 1,
    comment_id: 1002,
    created_at: "2023-09-21T10:30:00Z",
    updated_at: "2023-09-22T12:30:00Z",
    liked: 0,
    comments: [],
  },
  {
    review_id: 3,
    user_uid: 103,
    rated: 3.5,
    contents: "몇몇 트랙은 좋았지만, 전체적으로는 조금 아쉬웠어요.",
    title: "괜찮은 앨범",
    type_id: 2,
    comment_id: 1003,
    created_at: "2023-09-22T08:15:00Z",
    updated_at: "2023-09-22T09:15:00Z",
    liked: 0,
    comments: [],
  },
  {
    review_id: 4,
    user_uid: 104,
    rated: 2,
    contents: "기대했던 만큼의 완성도는 아니었습니다. 다음 앨범을 기대할게요.",
    title: "아쉬운 앨범",
    type_id: 3,
    comment_id: 1004,
    created_at: "2023-09-23T13:45:00Z",
    updated_at: "2023-09-23T14:45:00Z",
    liked: 0,
    comments: [],
  },
  {
    review_id: 5,
    user_uid: 105,
    rated: 4,
    contents: "전체적으로 훌륭했어요. 다시 듣고 싶은 트랙이 많습니다.",
    title: "훌륭한 앨범",
    type_id: 2,
    comment_id: 1005,
    created_at: "2023-09-24T09:20:00Z",
    updated_at: "2023-09-24T10:20:00Z",
    liked: 0,
    comments: [],
  },
];

export const mockChartData: ChartResponse[] = [
  {
    name: "노래 1",
    id: "1",
    preview: "미리 듣기 링크 1",
    album_name: "앨범 1",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-03-28",
    album_artists: [{ artists_name: "아티스트 1" }],
    rated: 4.8,
  },
  {
    name: "노래 2",
    id: "2",
    preview: "미리 듣기 링크 2",
    album_name: "앨범 2",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-09-20",
    album_artists: [{ artists_name: "아티스트 2" }],
    rated: 1.9,
  },
  {
    name: "노래 3",
    id: "3",
    preview: "미리 듣기 링크 3",
    album_name: "앨범 3",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-11-04",
    album_artists: [{ artists_name: "아티스트 3" }],
    rated: 4.6,
  },
  {
    name: "노래 4",
    id: "4",
    preview: "미리 듣기 링크 4",
    album_name: "앨범 4",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-05-01",
    album_artists: [{ artists_name: "아티스트 4" }],
    rated: 2.6,
  },
  {
    name: "노래 5",
    id: "5",
    preview: "미리 듣기 링크 5",
    album_name: "앨범 5",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-09-24",
    album_artists: [{ artists_name: "아티스트 5" }],
    rated: 4.1,
  },
  {
    name: "노래 6",
    id: "6",
    preview: "미리 듣기 링크 6",
    album_name: "앨범 6",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-12-14",
    album_artists: [{ artists_name: "아티스트 6" }],
    rated: 1.1,
  },
  {
    name: "노래 7",
    id: "7",
    preview: "미리 듣기 링크 7",
    album_name: "앨범 7",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-12-18",
    album_artists: [{ artists_name: "아티스트 7" }],
    rated: 4.9,
  },
  {
    name: "노래 8",
    id: "8",
    preview: "미리 듣기 링크 8",
    album_name: "앨범 8",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-01-19",
    album_artists: [{ artists_name: "아티스트 8" }],
    rated: 1.1,
  },
  {
    name: "노래 9",
    id: "9",
    preview: "미리 듣기 링크 9",
    album_name: "앨범 9",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-05-16",
    album_artists: [{ artists_name: "아티스트 9" }],
    rated: 3.0,
  },
  {
    name: "노래 10",
    id: "10",
    preview: "미리 듣기 링크 10",
    album_name: "앨범 10",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-03-28",
    album_artists: [{ artists_name: "아티스트 10" }],
    rated: 4.1,
  },
  {
    name: "노래 11",
    id: "11",
    preview: "미리 듣기 링크 11",
    album_name: "앨범 11",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-07-28",
    album_artists: [{ artists_name: "아티스트 11" }],
    rated: 3.0,
  },
  {
    name: "노래 12",
    id: "12",
    preview: "미리 듣기 링크 12",
    album_name: "앨범 12",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-05-19",
    album_artists: [{ artists_name: "아티스트 12" }],
    rated: 3.8,
  },
  {
    name: "노래 13",
    id: "13",
    preview: "미리 듣기 링크 13",
    album_name: "앨범 13",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-08-25",
    album_artists: [{ artists_name: "아티스트 13" }],
    rated: 1.9,
  },
  {
    name: "노래 14",
    id: "14",
    preview: "미리 듣기 링크 14",
    album_name: "앨범 14",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-06-14",
    album_artists: [{ artists_name: "아티스트 14" }],
    rated: 2.1,
  },
  {
    name: "노래 15",
    id: "15",
    preview: "미리 듣기 링크 15",
    album_name: "앨범 15",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-02-28",
    album_artists: [{ artists_name: "아티스트 15" }],
    rated: 1.0,
  },
  {
    name: "노래 16",
    id: "16",
    preview: "미리 듣기 링크 16",
    album_name: "앨범 16",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-02-27",
    album_artists: [{ artists_name: "아티스트 16" }],
    rated: 3.6,
  },
  {
    name: "노래 17",
    id: "17",
    preview: "미리 듣기 링크 17",
    album_name: "앨범 17",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-08-12",
    album_artists: [{ artists_name: "아티스트 17" }],
    rated: 2.7,
  },
  {
    name: "노래 18",
    id: "18",
    preview: "미리 듣기 링크 18",
    album_name: "앨범 18",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-06-27",
    album_artists: [{ artists_name: "아티스트 18" }],
    rated: 4.9,
  },
  {
    name: "노래 19",
    id: "19",
    preview: "미리 듣기 링크 19",
    album_name: "앨범 19",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-12-09",
    album_artists: [{ artists_name: "아티스트 19" }],
    rated: 2.8,
  },
  {
    name: "노래 20",
    id: "20",
    preview: "미리 듣기 링크 20",
    album_name: "앨범 20",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-08-26",
    album_artists: [{ artists_name: "아티스트 20" }],
    rated: 4.7,
  },
  {
    name: "노래 21",
    id: "21",
    preview: "미리 듣기 링크 21",
    album_name: "앨범 21",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-05-01",
    album_artists: [{ artists_name: "아티스트 21" }],
    rated: 1.1,
  },
  {
    name: "노래 22",
    id: "22",
    preview: "미리 듣기 링크 22",
    album_name: "앨범 22",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-01-25",
    album_artists: [{ artists_name: "아티스트 22" }],
    rated: 4.7,
  },
  {
    name: "노래 23",
    id: "23",
    preview: "미리 듣기 링크 23",
    album_name: "앨범 23",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-01-25",
    album_artists: [{ artists_name: "아티스트 23" }],
    rated: 2.8,
  },
  {
    name: "노래 24",
    id: "24",
    preview: "미리 듣기 링크 24",
    album_name: "앨범 24",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-12-23",
    album_artists: [{ artists_name: "아티스트 24" }],
    rated: 1.8,
  },
  {
    name: "노래 25",
    id: "25",
    preview: "미리 듣기 링크 25",
    album_name: "앨범 25",
    album_image: "https://picsum.photos/150/150",
    release_date: "2022-11-06",
    album_artists: [{ artists_name: "아티스트 25" }],
    rated: 2.0,
  },
  {
    name: "노래 26",
    id: "26",
    preview: "미리 듣기 링크 26",
    album_name: "앨범 26",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-02-06",
    album_artists: [{ artists_name: "아티스트 26" }],
    rated: 5.0,
  },
  {
    name: "노래 27",
    id: "27",
    preview: "미리 듣기 링크 27",
    album_name: "앨범 27",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-12-10",
    album_artists: [{ artists_name: "아티스트 27" }],
    rated: 4.6,
  },
  {
    name: "노래 28",
    id: "28",
    preview: "미리 듣기 링크 28",
    album_name: "앨범 28",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-03-26",
    album_artists: [{ artists_name: "아티스트 28" }],
    rated: 4.4,
  },
  {
    name: "노래 29",
    id: "29",
    preview: "미리 듣기 링크 29",
    album_name: "앨범 29",
    album_image: "https://picsum.photos/150/150",
    release_date: "2024-03-13",
    album_artists: [{ artists_name: "아티스트 29" }],
    rated: 2.2,
  },
  {
    name: "노래 30",
    id: "30",
    preview: "미리 듣기 링크 30",
    album_name: "앨범 30",
    album_image: "https://picsum.photos/150/150",
    release_date: "2023-04-09",
    album_artists: [{ artists_name: "아티스트 30" }],
    rated: 1.8,
  },
];

// 아티스트 목데이터
export const mockArtistsData: ArtistResponse[] = [
  {
    name: "아티스트 1",
    id: "1",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/1",
    rated: 4.1,
    genres: ["Latin", "Funk"],
  },
  {
    name: "아티스트 2",
    id: "2",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/2",
    rated: 1.8,
    genres: ["Jazz", "R&B"],
  },
  {
    name: "아티스트 3",
    id: "3",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/3",
    rated: 5.0,
    genres: ["Soul", "Pop"],
  },
  {
    name: "아티스트 4",
    id: "4",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/4",
    rated: 2.7,
    genres: ["Latin", "Classical"],
  },
  {
    name: "아티스트 5",
    id: "5",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/5",
    rated: 3.6,
    genres: ["Punk", "Blues"],
  },
  {
    name: "아티스트 6",
    id: "6",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/6",
    rated: 1.6,
    genres: ["Funk", "Electronic"],
  },
  {
    name: "아티스트 7",
    id: "7",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/7",
    rated: 2.5,
    genres: ["Electronic", "Pop"],
  },
  {
    name: "아티스트 8",
    id: "8",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/8",
    rated: 2.3,
    genres: ["Metal", "Reggae"],
  },
  {
    name: "아티스트 9",
    id: "9",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/9",
    rated: 2.6,
    genres: ["Blues", "House"],
  },
  {
    name: "아티스트 10",
    id: "10",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/10",
    rated: 5.0,
    genres: ["Jazz", "Pop"],
  },
  {
    name: "아티스트 11",
    id: "11",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/11",
    rated: 4.1,
    genres: ["House", "Funk"],
  },
  {
    name: "아티스트 12",
    id: "12",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/12",
    rated: 4.0,
    genres: ["Opera", "Folk"],
  },
  {
    name: "아티스트 13",
    id: "13",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/13",
    rated: 2.0,
    genres: ["Electronic", "Soul"],
  },
  {
    name: "아티스트 14",
    id: "14",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/14",
    rated: 1.9,
    genres: ["R&B", "Blues"],
  },
  {
    name: "아티스트 15",
    id: "15",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/15",
    rated: 1.6,
    genres: ["Latin", "Electronic"],
  },
  {
    name: "아티스트 16",
    id: "16",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/16",
    rated: 3.1,
    genres: ["Disco", "Folk"],
  },
  {
    name: "아티스트 17",
    id: "17",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/17",
    rated: 2.8,
    genres: ["Rock", "Disco"],
  },
  {
    name: "아티스트 18",
    id: "18",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/18",
    rated: 2.1,
    genres: ["Disco", "Soul"],
  },
  {
    name: "아티스트 19",
    id: "19",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/19",
    rated: 2.5,
    genres: ["Folk", "R&B"],
  },
  {
    name: "아티스트 20",
    id: "20",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/20",
    rated: 4.1,
    genres: ["Opera", "Folk"],
  },
  {
    name: "아티스트 21",
    id: "21",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/21",
    rated: 4.0,
    genres: ["Classical", "Opera"],
  },
  {
    name: "아티스트 22",
    id: "22",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/22",
    rated: 1.5,
    genres: ["Country", "Metal"],
  },
  {
    name: "아티스트 23",
    id: "23",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/23",
    rated: 4.7,
    genres: ["Metal", "Classical"],
  },
  {
    name: "아티스트 24",
    id: "24",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/24",
    rated: 4.4,
    genres: ["Funk", "Blues"],
  },
  {
    name: "아티스트 25",
    id: "25",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/25",
    rated: 3.9,
    genres: ["Pop", "R&B"],
  },
  {
    name: "아티스트 26",
    id: "26",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/26",
    rated: 1.0,
    genres: ["Punk", "House"],
  },
  {
    name: "아티스트 27",
    id: "27",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/27",
    rated: 2.0,
    genres: ["Rock", "Metal"],
  },
  {
    name: "아티스트 28",
    id: "28",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/28",
    rated: 2.7,
    genres: ["Techno", "Funk"],
  },
  {
    name: "아티스트 29",
    id: "29",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/29",
    rated: 4.4,
    genres: ["House", "Latin"],
  },
  {
    name: "아티스트 30",
    id: "30",
    image: "https://picsum.photos/150/150",
    spotify_url: "https://spotify.com/artist/30",
    rated: 1.9,
    genres: ["Classical", "Techno"],
  },
];
